config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :events, only: [:index, :show]

  post "/event_likes", to: 'events_users#create'

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get 'auth/:provider/callback', to: 'sessions#create'

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  before_validation { |artist| artist.display_name = display_name.downcase }
  has_many :artists_events
  has_many :events, through: :artists_events
end

app/models/artists_event.rb
class ArtistsEvent < ActiveRecord::Base
  belongs_to :artist
  belongs_to :event  
end

app/models/event.rb
class Event < ActiveRecord::Base
  reverse_geocoded_by :lat, :lng
  after_validation :reverse_geocode
  before_save :style_event_display
  before_save :parse_uri

  has_many :artists_events
  has_many :artists, through: :artists_events

  has_many :locations_events
  has_many :locations, through: :locations_events

  has_many :events_users
  has_many :users, through: :events_users

  belongs_to :venue

  scope :city,         -> (city)  { where("city ILIKE ?", city) }
  scope :state,        -> (state) { where("state ILIKE ?", state) }
  scope :display_name, -> (display_name) { where("display_name ILIKE ?", display_name) }
  scope :event_type,   -> (event_type) { where("event_type ILIKE ?",  event_type) }
  scope :artist_name, lambda { |artist_name|
    joins(:artists_events => :artist).where('artists.display_name' => artist_name)
  }

  scope :min_date, -> (min_date){ where("datetime > ?", min_date)}
  scope :max_date, -> (max_date){ where("datetime < ?", max_date)}


  def self.location(filter_location)
    lat, lng = filter_location[4..-1].split(",")
    near([lat, lng], 100)
  end


  def self.save_events(filtered_params)
    events = EventServices.events(filtered_params)

    parsed = JSON.parse(events)

    return false if parsed["resultsPage"]["results"].empty?

    parsed_events = parsed["resultsPage"]["results"]["event"]

    parsed_events.each do |event|
      created_event = find_or_create_by(
      display_name: event["displayName"],
      event_type:   event["type"],
      lat:          event["venue"]["lat"],
      lng:          event["venue"]["lng"],
      datetime:     event["start"]["date"],
      uri:          event["uri"]
      )

      created_event.venue = Venue.find_or_create_by(
      display_name: event["venue"]["displayName"],
      lat:          event["venue"]["lat"],
      lng:          event["venue"]["lng"],
      city:         event["venue"]["metroArea"]["displayName"],
      country:      event["venue"]["metroArea"]["country"]["displayName"]
      )

      event["performance"].each do |artist|
        artist = Artist.find_or_create_by(
        display_name: artist["displayName"]
        )

        ArtistsEvent.create(artist_id: artist.id, event_id: created_event.id)
      end
    end
    return true
  end

  def style_event_display
    if event_type.blank? || event_type == "Festival"
      self.datetime.strftime('%B %C, %Y')
    else event_type == "Concert"
      band, venue = display_name.split(" at ")
      self.artist = band

      place, show_date = venue.split("(")
      self.show_name = place
      self.date = show_date[0..-2] if !show_date.nil?
    end
  end

  def display_date
    datetime.strftime('%B %C, %Y')
  end

  def parse_uri
    self.uri = uri.split("?")[0]
  end
end

app/models/events_user.rb
class EventsUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :location_events
  has_many :events, through: :locations_events

  geocoded_by :location
  before_save :set_latitude_and_longitude

  def set_latitude_and_longitude
    result = Geocoder.coordinates(location)
    self.latitude = result[0]
    self.longitude = result[1]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events_users
  has_many :events, through: :events_users

  def self.find_or_create_from_auth(auth)
    user = User.find_or_create_by(provider: auth.provider, uid: auth.uid)
    user.name  = auth.info.name
    user.email = auth.info.email
    user.oauth_token = auth.credentials.token
    user.save!
    user
  end
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :likes

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def likes
    current_user.events_users.map do |like|
      Event.find(like.event_id).display_name
    end
  end

  def authorize!
    redirect_to root_path unless current_user
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    if params[:artist_name].nil? && params[:location].nil?
      @events = Event.all
    else
      events_found = Event.save_events(filtering_params(params))
      @events = Event.all
      if events_found
        filtering_params(params).each do |key, value|
          @events = @events.public_send(key, value) if value.present?
        end
      end
    end
  end

  def show
    @event = Event.find_by(id: params[:id])
  end

  def geocode_location(filtered)
    results = Geocoder.coordinates(filtered[:location])
    lat = results[0]
    lng = results[1]
    location_filter = "geo:#{lat},#{lng}"
    filtered[:location] = location_filter
    filtered
  end

  private

  def filtering_params(params)
    filtered = params.slice(:artist_name, :location, :min_date, :max_date).delete_if {|k,v| v.blank?}
    return geocode_location(filtered) if filtered[:location]
    filtered
  end
end

app/controllers/events_users_controller.rb
class EventsUsersController < ApplicationController

  def create
    @likes = EventsUser.create(user_id: current_user.id, event_id: params[:eventsusers][:event_id])
    flash[:success] = "This Event Has Been Successfully Added!"

    redirect_to :back
  end

  def destroy
    @likes = EventsUser.destroy(params[:eventsusers][:user_id], params[:eventsusers][:event_id])
  end
end

app/controllers/location_controller.rb
class LocationController < ApplicationController

  def create
    Location.create!(params[:location])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_or_create_from_auth(auth)
    if user
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = "Invalid Login"
      redirect_to root_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def auth
    (request.env['omniauth.auth'])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper

  def event_type_helper
    Event.all.map(&:event_type).uniq
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/index.html.erb
<div class="container search-tabs">
  <div class="row">
    <div class="col-md-4">
      <div class="side-bar">
        <%= render "shared/side_bar" %>
      </div>
    </div>
    <div class="col-md-offset-4">
      <div id='map-two' class='map'> </div>
      <script>
      L.mapbox.accessToken = 'pk.eyJ1IjoibHlkaWFzMzAzIiwiYSI6ImM0WG9rY28ifQ.bM1Nx1fsDmbAFLVP1f9Img';
      var map =  L.mapbox.map('map-two', 'lydias303.4498de5f',{scrollWheelZoom: true}).setView([39.828127, -98.579404], 4);;
      var myLayer = L.mapbox.featureLayer().addTo(map);
      var geojson = [
        {
          "type": "FeatureCollection",
          "features": [ <% @events.each do |ev| %>
            {
              "type": "Feature",
              "geometry": {
                "type": "Point",
                "coordinates": [
                  <%= ev.lng %>,
                  <%= ev.lat %>
                ]
              },
              "properties": {
                "url": "<%= request.env['HTTP_HOST']%>/events/<%= ev.id %>",
                "marker-symbol": "<%= ev.event_type == "festival" ? "campsite" : "music" %>",
                "marker-color": "<%= ev.event_type == "festival" ? "#e9620a" : "#e9620a" %>",
                "marker-size": "large",
                "display_name": "<%=  ev.display_name %><br>",
                "location": "<%=  ev.location %><br>",
                "event_type": "<%= ev.event_type %><br>"}
              },
              <% end %>]
            }
          ];


          myLayer.on('layeradd', function(e) {
            var marker = e.layer,
            feature = marker.feature;

            var popupContent =  '<a class="popup" href="http://' + feature.properties.url + '">' +
            feature.properties.display_name +
            feature.properties.event_type +
            '</a>';

            marker.bindPopup(popupContent,{
              closeButton: false,
              minWidth: 320
            });
          });

          myLayer.setGeoJSON(geojson);
          </script>
        </div>
      </div>
    </div>

app/views/events/show.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <% if @event.event_type == "Concert" %>
    <h1> <%= @event.artist %></h1>
    <div class="well event-show">
      <%= @event.show_name  %></br>
      <%= @event.date %></br>
      <%= @event.artists.map(&:display_name).join(", ") %></br>
      <%= link_to 'Find Tickets', @event.uri, class: "btn btn-lg btn-info", target: "_blank" %>
      <% else %>
      <h1><%= @event.display_name %></h1></br>
      <div class="well event-show">
        <%= @event.display_date %></br></br>
        <%= @event.artists.map(&:display_name).join(", ") %></br>
        <a class="btn btn-lg btn-info"  href=" <%= @event.uri %>">
          <i class="fa fa-ticket"></i>
          Find Tickets
        </a>
        <% end %>

        <% if !current_user.nil? && current_user.events.include?(@event) %>
        <h3> Liked </h3>
        <% elsif !current_user.nil? %>
        <%= render partial: 'shared/like_button', locals: {event: @event} %>
        <% else %>
        <h5>Log in With Facebook To Like This Event! </h5>
        <% end %>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WookBook</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <%= csrf_meta_tags %>
    <meta charset=utf-8 />
    <script src='https://api.tiles.mapbox.com/mapbox.js/v2.1.5/mapbox.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox.js/v2.1.5/mapbox.css' rel='stylesheet' />
  <style>
    body { margin:0; padding:0; }
    .map { position:absolute; top:0; bottom:0; width:100%; }
  </style>
</head>
<body>
  <% if current_page? root_path %>
    <div class="home-page-background">
  <% end %>
    <%= render "shared/nav_bar" %>
    <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>
    <%= yield %>
    <div class="row">
      <div class="col-md-12">
        <img class="footer-img" src="http://aclp3.c3cdn.com/wp/wp-content/themes/acl2013/img/desk-footer__bg.png" alt="" data-class="footer-stack--truck-trailer">
      </div>
    </div>
      <% if current_page? root_path %>
  </div>
  <% end %>
  </body>
</html>

app/views/refills/_snippet.html.erb
<td class="snippet">
  <div class="copy-source-container">
    <% if language == :javascript -%>
      <a href="javascript:void(0)" class="copy-source">Copy JavaScript</a>
      <a href="javascript:void(0)" class="copy-source copy-coffee">Copy CoffeeScript</a>
    <% elsif language == :markup -%>
      <a href="javascript:void(0)" class="copy-source">Copy HTML</a>
    <% else -%>
      <a href="javascript:void(0)" class="copy-source">Copy Scss</a>
    <% end -%>
  </div>
  <pre><code class="language-<%= language %>"><%== snippet %></code></pre>
</td>

app/views/shared/_like_button.html.erb
<%= form_tag "/event_likes", method: :post do %>
  <%= hidden_field_tag "eventsusers[event_id]", event.id %>
  <%= submit_tag 'Add To Likes', class: "btn btn-primary" %>
<% end %>

app/views/shared/_like_modal.html.erb
<div class="modal fade" id="likes-modal" tabindex="-1" role="dialog" aria-labelledby="likesModalLabel" aria-hidden="true">
  <div class="modal-dialog likes-modal">
    <div class="modal-content likes-modal">
      <div class="modal-header">
        <p>Your Favorite Festivals</p>
      </div>
      <div class="modal-body">
      <% if current_user.nil? %>
      <h2> Want to store your favorite Festivals?</h2>
      <li><a href="/auth/facebook">Login with <i class="fa fa-facebook-square"></i></a></li>
      <% elsif likes.nil? %>
      <h3> It looks like you haven't liked any festivals yet.<br>
      Go Check Some Out! <%= link_to "Browse Festivals", events_path %></h3>
      <% else %>
        <% likes.each do |like| %>
          <%= like %><br>
        <% end %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_login.html.erb
<div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class-"modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
      </div>
      <div class="modal-body">
        <%= bootstrap_form_for :session, url: login_path do |f| %>
          <%= f.text_field :email %>
          <%= f.password_field :password %>
          <%= f.submit "Log In" %>
        <% end %>
      </div>
      <a href="#" class="zocial facebook">Sign in with Facebook</a>
    </div>
  </div>
</div>

app/views/shared/_nav_bar.html.erb
<div class="navbar transparent navbar-static-top">
  <nav class="navbar-inner">
    <div class="navbar-header">
      <a class-"navbar-brand" href="/">Wook Book</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user.nil? %>
      <li><a href="/auth/facebook">Login with <i class="fa fa-facebook-square"></i></a></li>
      <li class="active"><a href="#" data-toggle="modal" data-target="#likes-modal" id="likes"><i class="fa fa-heart fa-sm"></i>Likes</a></li>
        <%= render "shared/like_modal" %>
      </li>
      <% else %>
      <li class="active"><a href="#" data-toggle="modal" data-target="#likes-modal" id="likes"><i class="fa fa-heart fa-sm"></i>Likes</a></li>
        <%= render "shared/like_modal" %>
      </li>
      <li><%= link_to "Log Out", logout_path, method: "DELETE" %></li>
      <% end %>
      </li>
    </ul>
  </nav>
</div>

app/views/shared/_side_bar.html.erb
<div class="tabbable search-tabs">
  <ul class="nav nav-tabs">
    <li class="active"><a href="#one" data-toggle="tab" class="basic">Basic Search</a></li>
    <li><a href="#twee" data-toggle="tab" class="advanced">Advanced Search</a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="one">
      <h2>Basic Search <i class="fa fa-search"></i></h2>
      <div class="tabbable">
        <div class="form">
          <%= bootstrap_form_tag url: "/events", method: "get" do |f| %>
          <%= f.text_field :artist_name, placeholder: "Artist", class: "connector" %>
          <%= f.text_field :location, placeholder: "Where? city/state/address", class: "connector" %>
          <%= f.submit "Filter", class: "btn btn-default connector" %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="tab-pane" id="twee">
      <h2>Advanced Search <i class="fa fa-search"></i></h2>
      <div class="tabbable">
        <div class="form advancedSearch">
          <%= bootstrap_form_tag url: "/events", method: "get", html: {id: "advancedSearch"} do |f| %>
          <%= f.text_field :artist_name, placeholder: "Artist", class: "connector" %>
          <%= f.text_field :location, placeholder: "Where? City/State/Address", class: "connector" %>
          <%= f.text_field :min_date, placeholder: "2015-MM-DD", class: "connector",  presence: true %>
          <%= f.text_field :max_date, placeholder: "2015-MM-DD", class: "connector",  presence: true%>
          <%= f.submit "Filter", class: "btn btn-default connector", id: "advancedSubmit" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  <%= javascript_tag do %>
    $(document).ready(function() {
      $(function($){
        $("#max_date").mask("2015-99-99");
        $("#min_date").mask("2015-99-99");
      });

      $("#advancedSubmit").on("click", function() {
        if($(".advancedSearch #location").val() === "") {
          alert("Please enter a location to search by date.");
          return false;
        }
      })
    });
  <% end %>
</script>

app/views/welcome/index.html.erb
<div class="top"></div>
<div class="banner">
  <%= image_tag "banner-no.png" %>
</div>
<div class="main">
  <div class="center"><div class="show-search"><a href="/events"><%= image_tag "planet.png" %></a></div></div>
</div>
<div class="bottom">
  <div class="left"></div>
  <div class="right"></div>
</div>
<div style="clear:both;"></div>
<footer>
  <div class="footer-elements">
    <div class="element1"></div>
    <div class="element2 social-element">
      <p>
        <a href="#"><i class="facebook fa fa-facebook"></i></a><a href="#"><i class="twitter fa fa-twitter"></i></a><a href="#"><i class="mail fa fa-envelope"></i><i class="info fa fa-info-circle"></i></a>
      </p>
    </div>
    <div class="element1"></div>
  </div>
</footer>
<div style="clear:both;"></div>
<div class="row featured">
  <div class="well col-md-2 col-md-offset-1 clearfix first-well">
    <a href="http://www.summercampfestival.com/"><img class="img-circle" src="http://loudwhispermedia.com/wp-content/uploads/2014/10/SummerCampLogo1-240x240.png" %></a>
  </div>
  <div class="well col-md-2 clearfix second-well">
    <a href="http://www.aclfestival.com/"><img class="img-circle" src="http://asleepatthewheel.com/wp-content/uploads/2013/01/530668_10151104519098030_1327768427_n.jpg"/></a>
  </div>
  <div class="well col-md-2 clearfix third-well">
    <a href="http://www.arisefestival.com/2015/"><img class="img-circle" src="http://ecowatch.com/wp-content/uploads/2014/07/arisefestfi.jpg" %></a>
  </div>
  <div class="well col-md-2 clearfix third-well">
    <a href="http://sasquatchfestival.com/"><img class="img-circle" src="http://www.takeashot.lv/wp-content/uploads/2014/11/sasquatch-2010-music-festival-poster-471x454.jpg" %>
  </div>
</div>